version: '3'
services:
  distance-tracker-service:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: 'distance-tracker-service'
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=local
      - PORT=3000
      - REDIS_HOST=redis
      - MONGOOSE_URL=mongodb://mongo:27017/distance_tracker
    command: sh -c "yarn dev"
    ports:
      - 3000:3000
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    expose:
      - 6379
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    expose:
      - 27017
